### PR TITLE
Changes to support multiple named processes

### PR DESCRIPTION
**Pull request by WorksButNotTested**
Added support for injecting into multiple processes:
either specifying the "-p" option multiple times,
or specifying "-a <name>" to inject into all named processes and watch for any new processes to inject.

### CODE REVIEW

**Comment by oleavr** [comment]
(Sorry for the delay!)  Would be great to land this, but I'm afraid there are some unresolved conflicts :crossed_swords:

**Comment by WorksButNotTested** [comment]
This should be re-based and ready to go now hopefully!

**Comment by oleavr** [comment]
Thanks! Landed with some minor tweaks in 7e88b7424cda26e6ad127968d68bfed121473b5d.

**Comment by WorksButNotTested** [comment]
Awesome thanks.

**Pull request closed without merging**
